### ISSUE TITLE
status is not found at /status (and neither /api/status)

### ISSUE THREAD

**Issue by UlrichHahn** [LuRhe/fhem-46_GoECharger#2]
'malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "This URI does not ex...") at ./FHEM/46_GoECharger.pm line 791.'

This appears on a GoE Charger with hardware version 3 and Software 050.2

I can read the JSON status at /api/status - but even when patching the module to read from this URI, it still generates the above result.

**Comment by LuRhe** [comment]
Everytime or sometimes? This module was designed vor API V1 and with HW V3 it is possible (or default?) to activate a newer API V2 [https://github.com/goecharger/go-eCharger-API-v2](url) . May be that's the problem?

At my GoE (HW V2, SW 041.0) same failure occures ~once a day  related to wifi connection problems. Unfortunatly I've no HW3 GoE.
Pls. check if:
- Fhem version up to date?
- libjson-perl up to date (system update/upgrade)?
- wifi stable?

You may also try to create a MQTT-Server at Fhem (m2s server) and activate mqtt at the box. The GoE sends every 5s the mqtt telegram as json to the mqtt server. The server (configured with autocreate) should automatically detect and create a device with json2 decode and Fhem should decode all data (same as http).
Generally I use today MQTT - this seams to be a better way instead using the polling module.

**Comment by UlrichHahn** [comment]
Ok - my fault: Indeed, APIv1 is deprecated and disabled by default. After activating there are readings coming in. 
MQTT seems to be configurable only when v1 is active.

Maybe integration of the current APIv2 into the module could be worth a thought?

Thanks for your quick reply!

Pls. check if:

    Fhem version up to date? - OK
    libjson-perl up to date (system update/upgrade)? - OK
    wifi stable? - Quite
